package drift

import (
	"encoding/json"
	"errors"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

func LoadContract(path string) (Contract, []byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Contract{}, nil, err
	}
	var contract Contract
	decoder := json.NewDecoder(strings.NewReader(string(raw)))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&contract); err != nil {
		return Contract{}, nil, err
	}
	if err := ValidateContract(contract); err != nil {
		return Contract{}, nil, err
	}
	return contract, raw, nil
}

func ValidateContract(contract Contract) error {
	if contract.Schema != ContractSchema || contract.DenominatorID == "" || contract.Total != 15 || len(contract.Cells) != 15 {
		return errors.New("INVALID_FIXED_DENOMINATOR")
	}
	seenIDs := make(map[string]bool, len(contract.Cells))
	seenActivities := make(map[string]bool, len(contract.Cells))
	for index, cell := range contract.Cells {
		if cell.Ordinal != index+1 || cell.ID == "" || cell.Activity == "" || cell.Name == "" || cell.Dimension == "" || cell.MetricDenominator != 1 || cell.Source == "" || cell.IR == "" || cell.GeneratedArtifact == "" || cell.Evaluator == "" {
			return errors.New("INVALID_FIXED_DENOMINATOR_CELL")
		}
		if seenIDs[cell.ID] || seenActivities[cell.Activity] {
			return errors.New("DUPLICATE_FIXED_DENOMINATOR_CELL")
		}
		seenIDs[cell.ID] = true
		seenActivities[cell.Activity] = true
	}
	return nil
}

func CompileSource(sourcePath string, source []byte, contract Contract, contractDigest string) (SemanticIR, error) {
	if err := ValidateContract(contract); err != nil {
		return SemanticIR{}, err
	}
	lines := strings.Split(string(source), "\n")
	if len(lines) == 0 || !strings.HasPrefix(strings.TrimSpace(lines[0]), "@gooo schema=\"gooo/semantic-drift/v1\"") {
		return SemanticIR{}, errors.New("GOOO_SOURCE_SCHEMA_HEADER_MISSING")
	}
	var activities []ActivityIR
	for lineNumber, rawLine := range lines {
		line := strings.TrimSpace(rawLine)
		if !strings.HasPrefix(line, "activity ") {
			continue
		}
		attrs, err := parseAttributes(strings.TrimPrefix(line, "activity "))
		if err != nil {
			return SemanticIR{}, fmt.Errorf("source line %d: %w", lineNumber+1, err)
		}
		activity := ActivityIR{
			ID: attrs["id"], Activity: attrs["activity"], Name: attrs["name"],
			Dimension: attrs["dimension"], Step: attrs["step"], Artifact: attrs["artifact"],
			Evaluator: attrs["evaluator"], SourceLine: lineNumber + 1,
		}
		if activity.ID == "" || activity.Activity == "" || activity.Name == "" || activity.Dimension == "" || activity.Step == "" || activity.Artifact == "" || activity.Evaluator == "" {
			return SemanticIR{}, fmt.Errorf("source line %d: INCOMPLETE_ACTIVITY_METADATA", lineNumber+1)
		}
		activities = append(activities, activity)
	}
	if len(activities) != contract.Total {
		return SemanticIR{}, errors.New("GOOO_SOURCE_DENOMINATOR_CARDINALITY_MISMATCH")
	}
	for index, cell := range contract.Cells {
		activity := activities[index]
		if activity.ID != cell.ID || activity.Activity != cell.Activity || activity.Name != cell.Name || activity.Dimension != cell.Dimension || activity.Artifact != cell.GeneratedArtifact || activity.Evaluator != cell.Evaluator {
			return SemanticIR{}, fmt.Errorf("GOOO_ACTIVITY_BINDING_MISMATCH_%d", cell.Ordinal)
		}
	}
	return SemanticIR{
		Schema: IRSchema, SourcePath: sourcePath, SourceDigest: DigestBytes(source),
		ContractPath: "contracts/semantic-drift-denominator-v1.json", ContractDigest: contractDigest,
		Activities: activities,
	}, nil
}

func SemanticIRBytes(ir SemanticIR) ([]byte, error) {
	raw, err := json.MarshalIndent(ir, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(raw, '\n'), nil
}

func GenerateGo(ir SemanticIR, semanticDigest string) ([]byte, error) {
	var builder strings.Builder
	builder.WriteString("// Code generated by gooo. DO NOT EDIT.\n\n")
	builder.WriteString("package generated\n\n")
	builder.WriteString("type Activity struct {\n")
	builder.WriteString("\tID string\n\tActivity string\n\tName string\n\tDimension string\n\tStep string\n\tArtifact string\n\tEvaluator string\n")
	builder.WriteString("}\n\n")
	fmt.Fprintf(&builder, "const SourcePath = %q\n", ir.SourcePath)
	fmt.Fprintf(&builder, "const SourceDigest = %q\n", ir.SourceDigest)
	fmt.Fprintf(&builder, "const SemanticIRPath = %q\n", "internal/generated/semantic-ir.json")
	fmt.Fprintf(&builder, "const SemanticIRDigest = %q\n", semanticDigest)
	fmt.Fprintf(&builder, "const ContractPath = %q\n", ir.ContractPath)
	fmt.Fprintf(&builder, "const ContractDigest = %q\n", ir.ContractDigest)
	fmt.Fprintf(&builder, "const ActivityCount = %d\n\n", len(ir.Activities))
	builder.WriteString("var Activities = []Activity{\n")
	for _, activity := range ir.Activities {
		fmt.Fprintf(&builder, "\t{ID: %q, Activity: %q, Name: %q, Dimension: %q, Step: %q, Artifact: %q, Evaluator: %q},\n", activity.ID, activity.Activity, activity.Name, activity.Dimension, activity.Step, activity.Artifact, activity.Evaluator)
	}
	builder.WriteString("}\n")
	return format.Source([]byte(builder.String()))
}

func parseAttributes(input string) (map[string]string, error) {
	attrs := map[string]string{}
	for position := 0; position < len(input); {
		for position < len(input) && input[position] == ' ' {
			position++
		}
		if position == len(input) {
			break
		}
		keyStart := position
		for position < len(input) && input[position] != '=' && input[position] != ' ' {
			position++
		}
		if keyStart == position || position >= len(input) || input[position] != '=' {
			return nil, errors.New("INVALID_ATTRIBUTE")
		}
		key := input[keyStart:position]
		if _, exists := attrs[key]; exists {
			return nil, errors.New("DUPLICATE_ATTRIBUTE")
		}
		position++
		if position >= len(input) || input[position] != '"' {
			return nil, errors.New("ATTRIBUTES_MUST_BE_QUOTED")
		}
		valueStart := position
		position++
		for position < len(input) {
			if input[position] == '"' && input[position-1] != '\\' {
				position++
				break
			}
			position++
		}
		if position > len(input) || position == 0 || input[position-1] != '"' {
			return nil, errors.New("UNTERMINATED_ATTRIBUTE")
		}
		value, err := strconv.Unquote(input[valueStart:position])
		if err != nil {
			return nil, err
		}
		attrs[key] = value
	}
	return attrs, nil
}
